index_view: page/index.html                                   #-------首页视图模板
menus:
 - title: 系统
   nav_menu:
    - title: 后台账号管理
      third_menu:
       - {title: 后台用户管理,view: page/system/admin_user_mgr.html,icon: ''}
    - title: 个人中心
      third_menu:
       - {title: 修改密码,view: page/system/admin_reset_password.html,icon: ''}
    - title: 系统工具
      third_menu:
       - {title: 模型工具,view: page/system/admin_model_tools.html,icon: ''}
